CREATE SCHEMA IF NOT EXISTS TokenGuard;

CREATE TABLE IF NOT EXISTS TokenGuard.users (
    id SERIAL PRIMARY KEY,
    telegramID BIGINT NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TokenGuard.tokens (
    id SERIAL PRIMARY KEY,
    userID BIGINT NOT NULL REFERENCES TokenGuard.users(id) ON DELETE CASCADE,
    token VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS TokenGuard.keys (
    id SERIAL PRIMARY KEY,
    tokenID BIGINT NOT NULL REFERENCES TokenGuard.tokens(id) ON DELETE CASCADE,
    secretKey BIGINT NOT NULL
);
